#! /bin/sh

${HOME}/.config/bspwm/autostart

bspc monitor DVI-I-0 -d 1 2 3
bspc monitor HDMI-0 -d 4 5 6

bspc config border_width         	2
bspc config window_gap           	4
bspc config single_monocle	 	false

bspc config -m DVI-I-0 top_padding	-4
#bspc config top_padding		0

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer	true

bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a BROWSER desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

##Color settings
bspc config normal_border_color		"#4C566A"
bspc config active_border_color		"#FF0099"
bspc config focused_border_color 	"#0066FF"
bspc config presel_feedback_color 	"#0066FF"
